### ISSUE TITLE
Change ErrorMessage error-message property to camelCase in JSON/XML output

### ISSUE THREAD

**Issue by heidielliott72** [PennState/commons-jaxrs#12]
src/main/java/edu/psu/swe/commons/jaxrs/ErrorMessage.java; some languages cannot handle hyphens in property names.

**Comment by smoyer64** [comment]
That's actually become our standard (which matches the SCIM specification).  The first letter should be lowercase.

**Comment by heidielliott72** [comment]
I would be happy to do the fix, but am unable to do a pull request.
